openapi: 3.0.3
info: 
  title: Заказ ресурсов в облаке
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1/
    description: Dev server
paths:
  /clouds:
    get:
      summary: Метод получения списка ресурсов облака
      tags:
        - Clouds
      operationId: getAllClouds
      responses:
        '200':
          description: Успешный ответ со списком ресурсов
          content:
            adplication/json:
              schema:
                $ref: '#/components/schemas/Clouds'
        default:
          description: Все остальное
          content:
            adplication/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Создание заказа на облако
      tags:
        - Clouds
      operationId: CreateCloud
      requestBody:
        content:
          adplication/json:
            schema:
              $ref: '#/components/schemas/Error'
      responses:
        '200':
          description: Заказ размещен
          content:
            adplication/json:
              schema:
                $ref: '#/components/schemas/Clouds'
        default:
          description: Все остальное
          content:
            adplication/json:
              schema:
                $ref: '#/components/schemas/Error'
  /clouds/{cloud_id}:
    get:
      summary: Метод получения заказа на облако по ID
      tags:
        - Clouds
      operationId: getCloudById
      parameters:
        - name: cloud_id
          in: path
          required: true
          description: Идентификатор заказа облака
          schema:
            type: string
          example: f102b615
      responses:
        '200':
          description: Успешный ответ заказом облака по ID
          content:
            adplication/json:
              schema:
                $ref: '#/components/schemas/Cloud'
        '404':
          description: Заказ с ID не найден
          content:
            adplication/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Все остальное
          content:
            adplication/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Метод удаления заказа
      tags: 
        - Clouds
      operationId: deleteCloudById
      parameters:
        - name: cloud_id
          in: path
          required: true
          description: Идентификатор заказа облака
          schema:
            type: string
          example: f1022b615
      responses:
        "200":
          description: Заказ удален
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Cloud"
        "404":
          description: Заказ с Id не найден
          content: 
            adplicatio/json:
              schema: 
                $ref: "#/components/schemas/Error"
        "default":
          description: Все остальное
          content:
            adplicatio/json:
              schema:
                $ref: "#/components/schemas/Error"
                
  /users:
    get:
      summary: Метод получения списка пользователей
      tags:
        - Users
      operationId: getAllUsers
      responses:
        '200':
          description: Успешный ответ со списком пользователей
          content:
            adplication/json:
              schema:
                $ref: '#/components/schemas/Users'
        default:
          description: Все остальное
          content:
            adplication/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Создание пользователя
      tags:
        - Users
      operationId: CreateUser
      requestBody:
        content:
          adplication/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Пользователь создан
          content:
            adplication/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Все остальное
          content:
            adplication/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/{user_id}:
    get:
      summary: Метод получения пользователя по ID
      tags:
        - Users
      operationId: getUserById
      parameters:
        - name: user_id
          in: path
          required: true
          description: Идентификатор заказа облака
          schema:
            type: string
          example: u102b615
      responses:
        '200':
          description: Успешный ответ с потльзователем по ID
          content:
            adplication/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Потльователь с ID не найден
          content:
            adplication/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Все остальное
          content:
            adplication/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Метод удаления пользователя
      tags: 
        - Users
      operationId: deleteUserById
      parameters:
        - name: user_id
          in: path
          required: true
          description: Идентификатор пользователя
          schema:
            type: string
          example: u1022b615
      responses:
        "200":
          description: Пользователь удален
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Пользователь с Id не найден
          content: 
            adplicatio/json:
              schema: 
                $ref: "#/components/schemas/Error"
        "default":
          description: Все остальное
          content:
            adplicatio/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Cloud:
      type: object
      required:
        - id_client
        - OS
        - RAM
        - CPU
        - HDD
      properties:
        cloud_id:
          type: string
          example: f102b615
        id_client:
          type: string
          example: f102b615
        OS:
          type: string
          enum:
            - Windows
            - Linux
          description: Операционная система сервера
        RAM:
          type: string
          example: 128
          description: Объем оперативной памяти
        CPU:
          type: string
          example: 8
          description: Количество ядер процессора
    Clouds:
      type: array
      items:
        $ref: '#/components/schemas/Cloud'
    User:
      type: object
      required:
        - user_id
        - firstName
        - lastName
        - password
      properties:
        user_id:
          type: string
          example: u102b615
        firstName:
          type: string
          example: Александр
        lastName:
          type: string
          example: Карпенко
        password:
          type: string
          example: sdkjh29vlk2j
          description: хэш пароля
    Users:
      type: array
      items:
        $ref: '#/components/schemas/User'
          
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
